version: '3'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather-mcp
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped